
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-webapp-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
        valueFiles:
        - values-prod.yaml
    path: helm
    repoURL: https://github.com/sentirelpoder/python-webapp
    targetRevision: HEAD
  syncPolicy: {}
